# Generated by Django 5.1.7 on 2025-03-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_message_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_hash',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'role', 'message_hash'), name='unique_message_in_conversation'),
        ),
    ]
